# Generated by Django 5.0.6 on 2024-06-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
