# Generated by Django 5.0.6 on 2024-06-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
